# -*- coding: UTF-8 -*-
import csv
import os
import re
from datetime import datetime
from pymongo import MongoClient
import json

# Connect to defualt local instance of MongoClient
client = MongoClient()

# Get database and collection
db = client.bpo
collection = db.mgr


def parse():
    collection.remove({})

    print "Importing Data"
    dir_path = os.path.dirname(os.path.realpath(__file__))
    print dir_path
    json_structure = {
        "VNUM": "violence_number",
        "RDATE": "report_date",
        "NCODE": "name_of_coder",
        "LUPC": "upazila",
        "LDIS": "district",
        "LUNW": "village",
        "WNONP": "woundednon_participant",
        "VREF": "violence_reference",
        "VCONT": "violent_event_continuation",
        "VTPRE": "violent_event_time_precision",
        "VTAGM": "violent_event_tag_multiple",
        "VTAGT": "violent_event_tag_trigger",
        "VTAGC": "violent_event_tag_continuation",
        "VDAY": "violence_day",
        "VMONT": "violence_month",
        "VYEAR": "violence_year",
        "VNONP": "violence_non_participants",
        "VTRIGC": "conflicting_trigger_of_violence",
        "AAVER": "arrested_averaged",
        "VPOL": "violence_police_role",
        "ANONP": "arrested_non_participant",
        "VREMU": "violence_report_multiple_events",
        "CAVER": "casualties_averaged",
        "VSOUR": "violence_source",
        "WAVER": "wounded_averaged",
        "VHART": "violent_event_hartal",
        "CNONP": "casualties_non_participant",
        "VACTB1": "violence_actor_b_1",
        "VACTB2": "violence_actor_b_2",
        "VACTB3": "violence_actor_b_3",
        "WOUACA": "total_number_of_wounded_reported_actor_a",
        "WOUACB": "total_number_of_wounded_reported_actor_b",
        "VTRIG1": "trigger_of_violence_1",
        "VTRIG2": "trigger_of_violence_2",
        "VTYP1": "violence_type_1",
        "VTYP2": "violence_type_2",
        "VTYP3": "violence_type_3",
        "WOUTAR": "total_number_of_wounded_reported_target",
        "ARRTAR": "total_number_of_arrested_reported_target",
        "ARRACB": "total_number_of_arrested_reported_actor_b",
        "CASTAR": "total_number_of_casualties_reported_target",
        "DPROP1": "destruction_of_property_1",
        "DPROP2": "destruction_of_property_2",
        "DPROP3": "destruction_of_property_3",
        "NDPRO1": "number_of_property_destroyed_1",
        "NDPRO2": "number_of_property_destroyed_2",
        "NDPRO3": "number_of_property_destroyed_3",
        "VTAR1": "violence_target_group_1",
        "VTAR2": "violence_target_group_2",
        "VTAR3": "violence_target_group_3",
        "VACTA1": "violence_actor_1",
        "VACTA2": "violence_actor_2",
        "VACTA3": "violence_actor_3",
        "CASACA": "total_number_of_casualties_reported_actor_a",
        "CASACB": "total_number_of_casualties_reported_actor_b",
        "ARRACA": "total_number_of_arrested_reported_actor_a"
    }
    violence_source = {
        "1": "Daily Star",
        "2": "Prothom Alu",
        "3": "Ittefaq",
        "4": "Inqilab",
        "5": "Manab Zamin"
    }
    violence_type_1 = {
        "0": "Unspecified",
        "000": "Unspecified",
        "100": "Battle/Clashes",
        "110": "Armed battle/clashes",
        "111": "Battle/clash with the use of arms",
        "112": "The arms used are not specified",
        "113": "Armed battle/clashes (throwing of projectiles)",
        "114": "Armed battle/clashes (knives)",
        "115": "Armed battle/clashes (tear gas)",
        "116": "Armed battle/clashes (rubber bullets)",
        "117": "Armed battle/clashes (rubber bullets)",
        "120": "Unarmed battle/clashes (fists)",
        "200": "Attack",
        "210": "Armed Attack",
        "211": "Armed Attack (guns, pistols)",
        "212": "Armed Attack (baton, stick, lathi, blunt weapons)",
        "213": "Armed Attack (throwing of projectiles)",
        "214": "Armed Attack (knives, sharp weapons)",
        "215": "Armed Attack (tear gas)",
        "216": "Armed battle/clashes (rubber bullets)",
        "217": "Armed battle/clashes (Water cannon)",
        "220": "Unarmed Attack (fists)",
        "300": "Destruction of property",
        "310": "No Arson",
        "320": "Arson",
        "400": "Bombing",
        "410": "Bombing (high impact)",
        "420": "Bombing (low impact)",
        "500": "Rape",
        "600": "Kidnapping, abduction",
        "700": "Hostage taking",
        "999": "Other*"
    }
    violence_trigger_1 = {
        "0": "Unspecified",
        "100": "Political",
        "110": "Election",
        "120": "Peace Process",
        "130": "Clash",
        "140": "Attack",
        "150": "Procession/demonstration",
        "160": "Hartal",
        "170": "Meeting",
        "180": "Assassination",
        "190": "Other*",
        "200": "Socio-Economic",
        "210": "Price Hike",
        "220": "Strike",
        "230": "Labour recruitment",
        "290": "Other*",
        "300": "Religious",
        "310": "Religious festival",
        "320": "Religious gathering",
        "390": "Other*",
        "400": "Judicial",
        "410": "Trial",
        "411": "Verdict",
        "420": "Arrest",
        "430": "Passing of new law",
        "490": "Other*",
        "500": "Remembrance",
        "510": "Independence",
        "520": "Language movement",
        "530": "Other National event",
        "540": "Death of leader",
        "590": "Other*",
        "600": "Access to Resource",
        "610": "Tender",
        "611": "Tender for public purpose",
        "612": "Tender for private purpose",
        "619": "Other*",
        "620": "Immoveable Property",
        "621": "Land",
        "622": "House",
        "623": "Farm",
        "624": "Factory",
        "629": "Other*",
        "630": "Moveable property",
        "631": "car",
        "632": "bike",
        "633": "boat",
        "634": "bus",
        "635": "Other vehicle*",
        "636": "farming equipment",
        "637": "industrial equipment",
        "638": "Money/cash",
        "639": "Other*",
        "699": "Other*",
        "700": "Position/job",
        "710": "Within organization",
        "720": "In public sector",
        "730": "In private sector",
        "799": "Other*",
        "800": "Organisational dynamics",
        "810": "Area Domination/Supremacy",
        "820": "Committee formation",
        "890": "Internal feud (non-specified)",
        "998": "Unknown",
        "999": "Other*"
    }

    event_location_district = {
        "0": "Unspecified",
        "100": "Barisal",
        "101": "Barguna",
        "102": "Barisal",
        "103": "Bhola",
        "104": "Jhalokati",
        "105": "Patuakhali",
        "106": "Pirojpur",
        "200": "Chittagong",
        "201": "Bandarban",
        "202": "Brahmanbaria",
        "203": "Chandpur",
        "204": "Chittagong",
        "205": "Comilla",
        "206": "Cox’s Bazar",
        "207": "Feni",
        "208": "Khagrachhari",
        "209": "Lakshmipur",
        "210": "Noakhali",
        "211": "Rangamati",
        "300": "Dhaka",
        "301": "Dhaka",
        "302": "Faridpur",
        "303": "Gazipur",
        "304": "Gopalganj",
        "305": "Jamalpur",
        "306": "Kishoreganj",
        "307": "Kishoreganj",
        "308": "Manikganj",
        "309": "Munshiganj",
        "310": "Mymensingh",
        "311": "Mymensingh",
        "312": "Narsingdi",
        "313": "Natrakona",
        "314": "Rajbari",
        "315": "Shariatpur",
        "316": "Sherpur",
        "317": "Tangail",
        "400": "Khulna",
        "401": "Bagarhat",
        "402": "Chuadanga",
        "403": "Jessore",
        "404": "Jhenaidah",
        "405": "Khulna",
        "406": "Kushtia",
        "407": "Magura",
        "408": "Meherpur",
        "409": "Narail",
        "410": "Satkhira",
        "500": "Rajshahi",
        "501": "Bogra",
        "502": "Joypurhat",
        "503": "Naogaon",
        "504": "Natore",
        "505": "Nawabganj",
        "506": "Pabna",
        "507": "Rajshahi",
        "508": "Sirajganj",
        "600": "Rangpur",
        "601": "Dinajpur",
        "602": "Gaibandha",
        "603": "Kurigram",
        "604": "Lalmonirhat",
        "605": "Nilphamari",
        "606": "Panchagarh",
        "607": "Rangpur",
        "608": "Thakurgoan",
        "700": "Sylhet",
        "701": "Habiganj",
        "702": "Maulvibazar",
        "703": "Sunamganj",
        "704": "Sylhet",
        "800": "Multiple"
    }
    violence_actor_1 = {
        "0": "Unspecified",
        "100": "State Actor",
        "110": "Law enforcement agencies",
        "111": "Police",
        "112": "Ansar",
        "113": "Rapid Action Battalion (RAB)",
        "114": "Range Reserve Force (RRF)",
        "115": "Special Armed Force (SAF)",
        "118": "Other*",
        "120": "Paramilitary",
        "121": "Border Guards Bangladesh",
        "128": "Other*",
        "130": "Military",
        "140": "Administration",
        "141": "Union/ward level",
        "142": "Upazilla level",
        "143": "District level",
        "144": "National level",
        "188": "Other*",
        "200": "Political Party",
        "210": "Awami League (AL)",
        "211": "Local Leader (Unspecified)",
        "212": "Local Leader (Union/ward/ Upazilla/Pourahava)",
        "213": "Local Leader (district/city)",
        "214": "National Leader (Unspecified)",
        "215": "Elected representative (national)",
        "216": "Former elected representative (national)",
        "217": "Member of Central Committee",
        "218": "Leader (Unspecified)",
        "219": "Activist",
        "220": "Bangladesh Nationalist Party (BNP)",
        "221": "Local Leader (Unspecified)",
        "222": "Local Leader (Union/ward/ Upazilla/Pourahava)",
        "223": "Local Leader (district/city)",
        "224": "National Leader (Unspecified)",
        "225": "Elected representative (national)",
        "226": "Former elected representative (national)",
        "227": "Member of Central Committee",
        "228": "Leader (Unspecified)",
        "229": "Activist",
        "230": "Jamaat-e-Islami (JI)",
        "231": "Local Leader (Unspecified)",
        "232": "Local Leader (Union/ward/ Upazilla/Pourahava)",
        "233": "Local Leader (district/city)",
        "234": "National Leader (Unspecified)",
        "235": "Elected representative (national)",
        "236": "Former elected representative (national)",
        "237": "Member of Central Committee",
        "238": "Leader (Unspecified)",
        "239": "Activist",
        "240": "Jatiya Party",
        "241": "Local Leader (Unspecified)",
        "242": "Local Leader (Union/ward/ Upazilla/Pourahava)",
        "243": "Local Leader (district/city)",
        "244": "National Leader (Unspecified)",
        "245": "Elected representative (national)",
        "246": "Former elected representative (national)",
        "247": "Member of Central Committee",
        "248": "Leader (Unspecified)",
        "249": "Activist",
        "250": "Left-Wing Parties",
        "251": "Communist Party of Bangladesh*",
        "252": "Socialist Party of Bangladesh*",
        "253": "Jatiyo Samajtantrik Dal (JSD)*",
        "254": "Worker’s Party of Bangladesh (WPB) *",
        "259": "Other left-wing party*",
        "260": "Islamist Parties",
        "261": "Bangladesh Khelafat Andolan",
        "262": "Islami Oikya Jote",
        "263": "Bangladesh Khelafat Majlish",
        "269": "Other Islamist Party*",
        "270": "Parbattya Chhattagram Jana Samhati Samiti (PCJSS)",
        "288": "Other*",
        "300": "Student Group",
        "310": "Bangladesh Chattro League",
        "311": "Local Leader (Unspecified)",
        "312": "Hall committee member",
        "313": "Hall Committee member (president/general secretary)",
        "314": "University/college committee member",
        "315": "University/college committee member (president/general secretary)",
        "316": "National Leader (Unspecified)",
        "317": "Member of Central committee",
        "318": "Member of Central committee (president/general secretary)",
        "319": "Activist",
        "320": "Jatiyatabadi Chhattro Dal",
        "321": "Local Leader (Unspecified)",
        "322": "Hall committee member",
        "323": "Hall Committee member (president/general secretary)",
        "324": "University/college committee member",
        "325": "University/college committee member (president/general secretary)",
        "326": "National Leader (Unspecified)",
        "327": "Member of Central committee",
        "328": "Member of Central committee (president/general secretary)",
        "329": "Activist",
        "330": "Islami Chattro Shibir",
        "331": "Local Leader (Unspecified)",
        "332": "Hall committee member",
        "333": "Hall Committee member (president/generalsecretary)",
        "334": "University/college committee member",
        "335": "University/college committee member (president/general secretary)",
        "336": "National Leader (Unspecified)",
        "337": "Member of Central committee",
        "338": "Member of Central committee (president/general secretary)",
        "339": "Activist",
        "340": "Jatiyo Chattro Samaj",
        "341": "Local Leader (Unspecified)",
        "342": "Hall committee member",
        "343": "Hall Committee member (president/general secretary)",
        "344": "University/college committee member",
        "345": "University/college committee member (president/general secretary)",
        "346": "National Leader (Unspecified)",
        "347": "Member of Central committee",
        "348": "Member of Central committee (president/general secretary)",
        "349": "Activist",
        "350": "Left-Wing Student Group",
        "351": "Chattro Union",
        "352": "Chattro Moitree",
        "353": "Chattro Federation",
        "358": "Other left-wing student group*",
        "360": "Islamist Student Group*",
        "388": "Other*",
        "400": "Youth (Jubo) Group",
        "410": "Jubo League",
        "411": "Local Leader (Unspecified)",
        "412": "Local Leader (Union/ward/ Upazilla/Pourahava)",
        "414": "Local Leader (district/ city)",
        "415": "National Leader (Unspecified)",
        "416": "Member of Central Committee",
        "417": "Leader (Unspecified)",
        "419": "Activist",
        "420": "Jubo Dal",
        "421": "Local Leader (Unspecified)",
        "422": "Local Leader (Union/ward/ Upazilla/Pourahava)",
        "424": "Local Leader (district/ city)",
        "425": "National Leader (Unspecified)",
        "426": "Member of Central Committee",
        "427": "Leader (Unspecified)",
        "429": "Activist",
        "430": "JI Jubo group",
        "431": "Local Leader (Unspecified)",
        "432": "Local Leader (Union/ward/ Upazilla/Pourahava)",
        "434": "Local Leader (district/ city)",
        "435": "National Leader (Unspecified)",
        "436": "Member of Central Committee",
        "437": "Leader (Unspecified)",
        "439": "Activist",
        "440": "Jatiya Juba Sanghati",
        "441": "Local Leader (Unspecified)",
        "442": "Local Leader (Union/ward/ Upazilla/Pourahava)",
        "444": "Local Leader (district/ city)",
        "445": "National Leader (Unspecified)",
        "446": "Member of Central Committee",
        "447": "Leader (Unspecified)",
        "449": "Activist",
        "450": "Left Wing Youth Groups*",
        "451": "Organizer (unspecified)",
        "452": "Local Leader (Unspecified)",
        "453": "National Leader (Unspecified)",
        "454": "Member of Central committee",
        "455": "Activist",
        "460": "Islamist Youth Groups*",
        "461": "Organizer (unspecified)",
        "462": "Local Leader (Unspecified)",
        "463": "National Leader (Unspecified)",
        "464": "Member of Central committee",
        "465": "Activist",
        "488": "Other*",
        "500": "Islamist Group",
        "510": "Jama'at-ul-Mujahideen Bangladesh",
        "520": "Hizb-ut-Tahrir",
        "530": "Hizb-ut-Towhid",
        "540": "Harkat-ul-Jihad-al Islami Bangladesh (HuJI-B)",
        "550": "Jagrata Muslim Janata Bangladesh (JMJB)",
        "560": "Hefajat-i-Islam",
        "588": "Other*",
        "600": "Alliance of actors",
        "610": "Awami League Centred Alliance",
        "611": "Multiple AL organizations (e.g. AL, BCL, BJL)",
        "612": "Multiple AL alliance organizations (AL, Grand alliance organizations)",
        "620": "Bangladesh Nationalist Party centered alliance",
        "621": "Multiple BNP organizations (e.g. BNP, BCD, BJD)",
        "622": "Multiple BNP alliance organizations (e.g. BNP, fourparty alliance)",
        "630": "Jamaat-e-Islami centered alliance",
        "631": "Multiple JI organizations (JI, ICS)",
        "632": "Multiple JI allied organizations (JI + other Islamist groups)",
        "640": "Alliance of left-wing parties",
        "650": "Alliance of Islamist Groups (nonJI)",
        "660": "Alliance of rebel groups",
        "661": "Alliance of CHT rebel groups",
        "662": "Alliance of left-wing rebel groups",
        "670": "Alliance of Trade Unions",
        "680": "Alliance of Alliance",
        "699": "Other*",
        "700": "Rebel Group",
        "710": "Purba Bangla Communist Party (PBCP)",
        "720": "United People’s Democratic Front (UPDF)",
        "730": "Shanti Bahini",
        "799": "Other*",
        "800": "Ethnic/religious Minority Groups",
        "810": "Ethnic minority group*",
        "811": "Garo/Mandi",
        "812": "Chakma",
        "813": "Marma",
        "814": "Tripura",
        "815": "Tanchangyas",
        "816": "Chak",
        "817": "Other CHT group*",
        "819": "Other*",
        "820": "Ethnic minority organization*",
        "830": "Religious minority group",
        "831": "Hindu",
        "832": "Buddhist",
        "833": "Christian",
        "839": "Other*",
        "840": "Religious minority organization*",
        "900": "Occupational group/organisation",
        "910": "Workers (non-organised)",
        "920": "Trade Union",
        "921": "Bangladesh Jatio Sramik League",
        "922": "Bangladesh Jatiyatabadi Sramik Dal",
        "923": "Bangladesh Jatiyo Sarmik Jote",
        "929": "Other*",
        "930": "Other worker’s organization*",
        "940": "Farmers (non-organised)",
        "950": "Farmer’s organisation",
        "951": "Bangladesh Krishak League",
        "952": "Bangladesh Khetmajur Union",
        "959": "Other*",
        "960": "Combination of workers and peasants",
        "970": "White collar workers",
        "980": "Management",
        "988": "Other*",
        "995": "Unidentified/unknown",
        "996": "Criminal (known)",
        "997": "journalist",
        "998": "Civilian/non-participants*",
        "999": "Other*"
    }
    violence_police_role = {
        "100": "Police not mentioned",
        "200": "Police is participant in the violent event from the start",
        "322": "Police participates in violent event on side of VACTA",
        "300": "Police arrives during the violent event",
        "310": "Police remains inactive during violent event",
        "320": "Police intervenes during the violent event ",
        "321": "Police separates sides in violent event",
        "323": "Police participates in violent event on side of VACTA",
        "400": "Police arrives after the violent event"
    }
    destruction_of_property={
        "0": "Unspecified",
        "100": "Agrarian",
        "110": "Fields",
        "120": "Harvested or stored crops",
        "130": "Farm Machinery",
        "140": "Farm Buildings",
        "150": "Farm Buildings",
        "199": "Other*",
        "200": "Industrial",
        "210": "Factory structure/building",
        "211": "Garments",
        "218": "Other",
        "220": "Machines",
        "221": "Garments",
        "228": "Other",
        "299": "Other*",
        "300": "Commercial",
        "310": "Shop",
        "320": "Market",
        "330": "Restaurant",
        "340": "Bank",
        "350": "Newspaper office",
        "360": "Warehouse",
        "370": "Harbour/port facilities",
        "380": "Filling station",
        "399": "Other*",
        "400": "Public facilities",
        "410": "Train station",
        "420": "Bus station",
        "430": "Public streets/squares",
        "440": "Monument",
        "450": "Meeting Hall",
        "460": "School Building",
        "470": "University/College building",
        "499": "Other*",
        "500": "Government property",
        "510": "Building",
        "511": "Office of local government (city, pourashava, union)",
        "512": "Office of district government",
        "513": "Office of central government",
        "514": "Parliament",
        "519": "Other*",
        "520": "Government vehicle",
        "521": "Police car",
        "522": "Government car",
        "522": "Other*",
        "599": "Other*",
        "600": "Religious building",
        "610": "Muslim",
        "620": "Hindu",
        "630": "Buddhist",
        "640": "Christian",
        "699": "Other*",
        "700": "Residence",
        "710": "House (general)",
        "720": "House (residence politician)",
        "730": "Apartment",
        "740": "Hotel",
        "799": "Other*",
        "800": "Transport/Vehicles",
        "810": "Rickshaw",
        "820": "CNG",
        "830": "Motorbike",
        "840": "Car",
        "850": "Bus",
        "860": "Train",
        "870": "Boat",
        "880": "Other private transport*",
        "890": "Other public transport*",
        "900": "Organizational office/headquarters",
        "910": "Political party",
        "911": "Office",
        "912": "Headquarters",
        "920": "Student group",
        "921": "Office",
        "922": "Headquarters",
        "930": "Youth Group",
        "931": "Office",
        "932": "Headquarters",
        "940": "Labour Union ",
        "941": "Office",
        "942": "Headquarters",
        "990": "Other*",
        "997": "Furniture",
        "998": "Banner",
        "999": "Other*"
    }

    upazila = {
        "100": "BARISAL DIVISION",
        "101": "BARGUNA DISTRICT",
        "101001": "Barguna",
        "101002": "Amtali",
        "101003": "Bamna",
        "101004": "Betagi",
        "101005": "Patharghata",
        "101006": "Taltoli",
        "102": "BARISAL DISTRICT",
        "102001": "Barisal",
        "102002": "Agailjhara",
        "102003": "Babuganj",
        "102004": "Bakerganj",
        "102005": "Banaripara",
        "102006": "Gaurnadi",
        "102007": "Hizla",
        "102008": "Mehendiganj",
        "102009": "Muladi",
        "102010": "Wazirpur",
        "103": "BHOLA DISTRICT",
        "103001": "Bhola",
        "103002": "Burhanuddin",
        "103003": "Char Fasson",
        "103004": "Daulatkhan",
        "103005": "Lalmohan",
        "103006": "Manpura",
        "103007": "Tazumuddin",
        "104": "JHALOKATI DISTRICT",
        "104001": "Jhalokati",
        "104002": "Kathalia",
        "104003": "Nalchity",
        "104004": "Rajapur",
        "105": "PATUAKHALI DISTRICT",
        "105001": "Patuakhali",
        "105002": "Dashmina",
        "105003": "Galachipa",
        "105004": "Kalapara",
        "105005": "Mirzaganj",
        "105006": "Bauphal",
        "105007": "Rangabali",
        "105008": "Dumki",
        "106": "PIROJPUR DISTRICT",
        "106001": "Pirojpur",
        "106002": "Kawkhali",
        "106003": "Mathbaria",
        "106004": "Nazirpur",
        "106005": "Bhandaria",
        "106006": "Nesarabad/Swarupkati",
        "106007": "Zianagor",
        "200": "CHITTAGONG DIVISION",
        "201": "BANDARBAN DISTRICT",
        "201001": "Bandarban",
        "201002": "Ali Kadam",
        "201003": "Lama",
        "201004": "Naikhongchhari",
        "201005": "Rowangchhari",
        "201006": "Ruma",
        "201007": "Thanchi",
        "202": "BRAHMANBARIA DISTRICT",
        "202001": "Brahmanbaria",
        "202002": "Bancharampur",
        "202003": "Akhaura",
        "202004": "Kasba",
        "202005": "Nabinagar",
        "202006": "Nasirnagar",
        "202007": "Sarail",
        "202008": "Ashuganj",
        "202009": "Bijoynagar",
        "203": "CHANDPUR DISTRICT",
        "203001": "Chandpur",
        "203002": "Faridganj",
        "203003": "Haimchar",
        "203004": "Haziganj",
        "203005": "Kachua",
        "203006": "Matlab Dakshin",
        "203006": "Matlab Uttar",
        "203007": "Shahrasti",
        "204": "CHITTAGONG DISTRICT",
        "204001": "Chittagong",
        "204002": "Anwara",
        "204003": "Banshkhali",
        "204004": "Boalkhali",
        "204005": "Chandanaish",
        "204006": "Fatikchhari",
        "204006": "Hathazari",
        "204007": "Karnaphuli",
        "204008": "Lohagara",
        "204009": "Mirsharai",
        "204010": "Patiya",
        "204011": "Rangunia",
        "204012": "Raozan",
        "204013": "Sandwip",
        "204014": "Satkania",
        "204015": "Sitakunda",
        "205": "COMILLA DISTRICT",
        "205001": "Comilla",
        "205002": "South Comilla",
        "205003": "Barura",
        "205004": "Brahmanpara",
        "205005": "Burichang",
        "205006": "Chandina",
        "205007": "Chauddagram",
        "205008": "Daudkandi",
        "205009": "Debidwar",
        "205010": "Homna",
        "205011": "Laksam",
        "205012": "Muradnagar",
        "205013": "Nangalkot",
        "205014": "Meghna",
        "205015": "Titash",
        "205016": "Monohargonj",
        "206": "COX'S BAZAR DISTRICT",
        "206001": "Cox's Bazar",
        "206002": "Chakaria",
        "206003": "Kutubdia",
        "206004": "Maheshkhali",
        "206005": "Ramu",
        "206006": "Teknaf",
        "206007": "Ukhia",
        "206008": "Pekua",
        "207": "FENI DISTRICT",
        "207001": "Feni",
        "207002": "Chhagalnaiya",
        "207003": "Daganbhuiyan",
        "207004": "Parshuram",
        "207005": "Sonagazi",
        "207006": "Fulgazi",
        "208": "KHAGRACHHARI DISTRICT",
        "208001": "Khagrachhari Sadr",
        "208002": "Dighinala",
        "208003": "Lakshmichhari",
        "208004": "Mahalchhari",
        "208005": "Manikchhari",
        "208006": "Matiranga",
        "208007": "Panchhari",
        "208008": "Ramgarh",
        "209": "LAKSHMIPUR DISTRICT",
        "209001": "Lakshmipur",
        "209002": "Raipur",
        "209003": "Ramganj",
        "209004": "Ramgati",
        "209005": "Kamalnagar",
        "210": "NOAKHALI DISTRICT",
        "210001": "Noakhali",
        "210002": "Begumganj",
        "210003": "Chatkhil",
        "210004": "Companiganj",
        "210005": "Hatiya",
        "210006": "Senbagh",
        "210007": "Sonaimuri",
        "210008": "Subarnachar",
        "210009": "Kabirhat",
        "211": "RANGAMATI DISTRICT",
        "211001": "Rangamati",
        "211002": "Bagaichhari",
        "211003": "Barkal",
        "211004": "Kawkhali (Betbunia)",
        "211005": "Belaichhari",
        "211006": "Kaptai",
        "211007": "Juraichhari",
        "211008": "Langadu",
        "211009": "Naniyachar",
        "211010": "Rajasthali",
        "300": "DHAKA DIVISION",
        "301": "DHAKA DISTRICT",
        "301001": "Dhaka",
        "301002": "Dhamrai",
        "301003": "Dohar",
        "301004": "Keraniganj",
        "301005": "Nawabganj",
        "301006": "Savar",
        "302": "FARIDPUR DISTRICT",
        "302001": "Faridpur",
        "302002": "Alfadanga",
        "302003": "Bhanga",
        "302004": "Boalmari",
        "302005": "Charbhadrasan",
        "302006": "Madhukhali",
        "302007": "Nagarkanda",
        "302008": "Sadarpur",
        "302009": "Saltha",
        "303": "GAZIPUR DISTRICT",
        "303001": "Gazipur City/Sadar",
        "303002": "Kaliakair",
        "303003": "Kaliganj",
        "303004": "Kapasia",
        "303005": "Sreepur",
        "304": "GOPALGANJ DISTRICT",
        "304001": "Gopalganj",
        "304002": "Kashiani",
        "304003": "Kotalipara",
        "304004": "Muksudpur",
        "304005": "Tungipara",
        "305": "JAMALPUR DISTRICT",
        "305001": "Jamalpur",
        "305002": "Baksiganj",
        "305003": "Dewanganj",
        "305004": "Islampur",
        "305005": "Madarganj",
        "305006": "Melandaha",
        "305007": "Sarishabari",
        "306": "KISHOREGANJ DISTRICT",
        "306001": "Kishoreganj",
        "306002": "Austagram",
        "306003": "Bajitpur",
        "306004": "Bhairab",
        "306005": "Hossainpur",
        "306006": "Itna",
        "306007": "Karimganj",
        "306008": "Katiadi",
        "306009": "Kuliarchar",
        "306010": "Mithamain",
        "306011": "Nikli",
        "306012": "Pakundia",
        "306013": "Tarail",
        "307": "MADARIPUR DISTRICT",
        "307001": "Madaripur",
        "307002": "Rajoir",
        "307003": "Kalkini",
        "307004": "Shibchar",
        "308": "MANIKGANJ DISTRICT",
        "308001": "Manikgonj",
        "308002": "Daulatpur",
        "308003": "Ghior",
        "308004": "Harirampur",
        "308005": "Saturia",
        "308006": "Shivalaya",
        "308007": "Singair",
        "309": "MUNSHIGANJ DISTRICT",
        "309001": "Munshiganj",
        "309002": "Gazaria",
        "309003": "Lohajang",
        "309004": "Sirajdikhan",
        "309005": "Sreenagar",
        "309006": "Tongibari",
        "310": "MYMENSINGH DISTRICT",
        "310001": "Mymensingh",
        "310002": "Bhaluka",
        "310003": "Dhobaura",
        "310004": "Fulbaria",
        "310005": "Gaffargaon",
        "310006": "Gauripur",
        "310007": "Haluaghat",
        "310008": "Ishwarganj",
        "310009": "Muktagachha",
        "310010": "Nandail",
        "310011": "Phulpur",
        "310012": "Trishal",
        "310013": "Tara Khanda",
        "311": "NARAYANGANJ DISTRICT",
        "311001": "Narayanganj City/Sadar",
        "311002": "Araihazar",
        "311003": "Bandar",
        "311004": "Rupganj",
        "311005": "Sonargaon",
        "312": "NARSINGDI DISTRICT",
        "312001": "Narsingdi",
        "312002": "Belabo",
        "312003": "Monohardi",
        "312004": "Palash",
        "312005": "Raipura",
        "312006": "Shibpur",
        "313": "NETROKONA DISTRICT",
        "313001": "Netrokona",
        "313002": "Atpara",
        "313003": "Barhatta",
        "313004": "Durgapur",
        "313005": "Khaliajuri",
        "313006": "Kalmakanda",
        "313007": "Kendua",
        "313008": "Madan",
        "313009": "Mohanganj",
        "313010": "Purbadhala",
        "314": "RAJBARI DISTRICT",
        "314001": "Rajbari",
        "314002": "Baliakandi",
        "314003": "Goalandaghat",
        "314004": "Pangsha",
        "314005": "Kalukhali",
        "315": "SHARIATPUR DISTRICT",
        "315001": "Shariatpur",
        "315002": "Bhedarganj",
        "315003": "Damudya",
        "315004": "Gosairhat",
        "315005": "Naria",
        "315006": "Zajira",
        "315007": "Shakhipur",
        "316": "SHERPUR DISTRICT",
        "316001": "Sherpur",
        "316002": "Jhenaigati",
        "316003": "Nakla",
        "316004": "Nalitabari",
        "316005": "Sreebardi",
        "317": "TANGAIL DISTRICT",
        "317001": "Tangail",
        "317002": "Gopalpur",
        "317003": "Basail",
        "317004": "Bhuapur",
        "317005": "Delduar",
        "317006": "Ghatail",
        "317007": "Kalihati",
        "317008": "Madhupur",
        "317009": "Mirzapur",
        "317010": "Nagarpur",
        "317011": "Sakhipur",
        "317012": "Dhanbari",
        "400": "KHULNA DIVISION",
        "401": "BAGERHAT DISTRICT",
        "401001": "Bagerhat",
        "401002": "Chitalmari",
        "401003": "Fakirhat",
        "401004": "Kachua",
        "401005": "Mollahat",
        "401006": "Mongla",
        "401007": "Morrelganj",
        "401008": "Rampal",
        "401009": "Sarankhola",
        "402": "CHUADANGA DISTRICT",
        "402001": "Chuadanga",
        "402002": "Alamdanga",
        "402003": "Damurhuda",
        "402004": "Jibannagar",
        "403": "JESSORE DISTRICT",
        "403001": "Jessore",
        "403002": "Abhaynagar",
        "403003": "Bagherpara",
        "403004": "Chaugachha",
        "403005": "Jhikargachha",
        "403006": "Keshabpur",
        "403007": "Manirampur",
        "403008": "Sharsha",
        "404": "JHENAIDA DISTRICT",
        "404001": "Jhenaidah",
        "404002": "Harinakunda",
        "404003": "Kaliganj",
        "404004": "Kotchandpur",
        "404005": "Maheshpur",
        "404006": "Shailkupa",
        "405": "KHULNA DISTRICT",
        "405001": "Khulna City/Kotwali Thana",
        "405002": "Batiaghata",
        "405003": "Dacope",
        "405004": "Dumuria",
        "405005": "Dighalia",
        "405006": "Koyra",
        "405007": "Paikgachha",
        "405008": "Phultala",
        "405009": "Rupsha",
        "405010": "Terokhada",
        "405011": "Daulatpur Thana",
        "405012": "Khalishpur Thana",
        "405013": "Khan Jahan Ali Thana",
        "401014": "Sonadanga Thana",
        "405015": "Harintana Thana",
        "406": "KUSHTIA DISTRICT",
        "406001": "Kushtia",
        "406002": "Bheramara",
        "406003": "Daulatpur",
        "406004": "Khoksa",
        "406005": "Kumarkhali",
        "406006": "Mirpur",
        "407": "MAGURA DISTRICT",
        "407001": "Magura",
        "407002": "Mohammadpur",
        "407003": "Shalikha",
        "407004": "Sreepur",
        "408": "MEHERPUR DISTRICT",
        "408001": "Meherpur",
        "408002": "Gangni",
        "408003": "Mujibnagar",
        "409": "NARAIL DISTRICT",
        "409001": "Narail",
        "409002": "Kalia",
        "409003": "Lohagara",
        "409004": "Naragati Thana",
        "410": "SATKHIRA DISTRICT",
        "410001": "Satkhira",
        "410002": "Assasuni",
        "410003": "Debhata",
        "410004": "Kalaroa",
        "410005": "Kaliganj",
        "410006": "Shyamnagar",
        "410007": "Tala",
        "500": "RAJSHAHI DIVISION ",
        "501": "BOGRA DISTRICT",
        "501001": "Bogra",
        "501002": "Adamdighi",
        "501003": "Dhunat",
        "501004": "Dhupchanchia",
        "501005": "Gabtali",
        "501006": "Kahaloo",
        "501007": "Nandigram",
        "501008": "Sariakandi",
        "501009": "Shajahanpur",
        "501010": "Sherpur",
        "501011": "Shibganj",
        "501012": "Sonatola",
        "502": "JOYPURHAT DISTRICT",
        "502001": "Joypurhat",
        "502002": "Akkelpur",
        "502003": "Kalai",
        "502004": "Khetlal",
        "502005": "Panchbibi",
        "503": "NAOGAON DISTRICT",
        "503001": "Naogaon",
        "503002": "Atrai",
        "503003": "Badalgachhi",
        "503004": "Manda",
        "503005": "Dhamoirhat",
        "503006": "Mohadevpur",
        "503007": "Niamatpur",
        "503008": "Patnitala",
        "503009": "Porsha",
        "503010": "Raninagar",
        "503011": "Sapahar",
        "504": "NATORE DISTRICT",
        "504001": "Natore",
        "504002": "Bagatipara",
        "504003": "Baraigram",
        "504004": "Gurudaspur",
        "504005": "Lalpur",
        "504006": "Singra",
        "504007": "Naldanga",
        "505": "NAWABGANJ DISTRICT",
        "505001": "Nawabganj",
        "505002": "Bholahat",
        "505003": "Gomastapur",
        "505004": "Nachole",
        "505005": "Shibganj",
        "506": "PABNA DISTRICT",
        "506001": "Pabna",
        "506002": "Ataikula",
        "506003": "Atgharia",
        "506004": "Bera",
        "506005": "Bhangura",
        "506006": "Chatmohar",
        "506007": "Faridpur",
        "506008": "Ishwardi",
        "506009": "Santhia",
        "506010": "Sujanagar",
        "507": "RAJSHAHI DISTRICT",
        "507001": "Rajshahi City",
        "507002": "Bagha",
        "507003": "Bagmara",
        "507004": "Charghat",
        "507005": "Durgapur",
        "507006": "Godagari",
        "507007": "Mohanpur",
        "507008": "Paba",
        "507009": "Puthia",
        "507010": "Tanore",
        "508": "SIRAJGANJ DISTRICT",
        "508001": "Sirajganj",
        "508002": "Belkuchi",
        "508003": "Chauhali",
        "508004": "Kamarkhanda",
        "508005": "Kazipur",
        "508006": "Raiganj",
        "508007": "Shahjadpur",
        "508008": "Tarash",
        "508009": "Ullahpara",
        "600": "RANGPUR DIVISION",
        "601": "DINAJPUR DISTRICt",
        "601001": "Dinajpur",
        "601002": "Birampur",
        "601003": "Birganj",
        "601004": "Biral",
        "601005": "Bochaganj",
        "601006": "Chirirbandar",
        "601007": "Phulbari",
        "601008": "Ghoraghat",
        "601009": "Hakimpur",
        "601010": "Kaharole",
        "601011": "Khansama",
        "601012": "Nawabganj",
        "601013": "Parbatipur",
        "602": "GAIBANDHA DISTRICT",
        "602001": "Gaibandha",
        "602002": "Phulchhari",
        "602003": "Gobindaganj",
        "602004": "Palashbari",
        "602005": "Sadullapur",
        "602006": "Sughatta",
        "602007": "Sundarganj",
        "603": "KURIGRAM DISTRICT",
        "603001": "Kurigram",
        "603002": "Bhurungamari",
        "603003": "Char Rajibpur ",
        "603004": "Chilmari",
        "603005": "Phulbari",
        "603006": "Nageshwari",
        "603007": "Rajarhat",
        "603008": "Raomari",
        "603009": "Ulipur",
        "604": "LALMONIRHAT DISTRICT",
        "604001": "Lalmonirhat",
        "604002": "Aditmari",
        "604003": "Hatibandha",
        "604004": "Kaliganj",
        "604005": "Patgram",
        "605": "NILPHAMARI DISTRICT",
        "605001": "Nilphamari",
        "605002": "Dimla",
        "605003": "Domar",
        "605004": "Jaldhaka",
        "605005": "Kishoreganj",
        "605006": "Saidpur",
        "606": "PANCHAGARH DISTRICT",
        "606001": "Panchagarh",
        "606002": "Atwari",
        "606003": "Boda",
        "606004": "Debiganj",
        "606005": "Tetulia",
        "607": "RANGPUR DISTRICT",
        "607001": "Rangpur",
        "607002": "Badarganj",
        "607003": "Gangachhara",
        "607004": "Kaunia",
        "607005": "Mithapukur",
        "607006": "Pirgachha",
        "607007": "Pirganj",
        "607008": "Taraganj",
        "608": "THAKURGAON DISTRICT",
        "608001": "Thakurgaon",
        "608002": "Baliadangi",
        "608003": "Haripur",
        "608004": "Pirganj",
        "608005": "Ranisankail",
        "701": "HABIGANJ DISTRICT",
        "701001": "Habiganj",
        "701002": "Ajmiriganj",
        "701003": "Bahubal",
        "701004": "Baniachong",
        "701005": "Chunarughat",
        "701006": "Lakhai",
        "701007": "Madhabpur",
        "701008": "Nabiganj",
        "702": "MOULVIBAZAR DISTRICT",
        "702001": "Moulvibazar",
        "702002": "Barlekha",
        "702003": "Kamalganj",
        "702004": "Kulaura",
        "702005": "Rajnagar",
        "702006": "Sreemangal",
        "702007": "Juri",
        "703": "SUNAMGANJ DISTRICT",
        "703001": "Sunamganj",
        "703002": "Bishwamvarpur",
        "703003": "Chhatak",
        "703004": "Derai",
        "703005": "Dharamapasha",
        "703006": "Dowarabazar",
        "703007": "Jagannathpur",
        "703008": "Jamalganj",
        "703009": "Sullah",
        "703010": "Tahirpur",
        "703011": "Dakshin Sunamganj",
        "704": "SYLHET DISTRICT",
        "704001": "Sylhet",
        "704002": "Balaganj",
        "704003": "Beanibazar",
        "704004": "Bishwanath",
        "704005": "Companigonj",
        "704006": "Fenchuganj",
        "704007": "Golapganj",
        "704008": "Gowainghat",
        "704009": "Jaintiapur",
        "704010": "Kanaighat",
        "704011": "Zakiganj",
        "704012": "South Surma",
        "704013": "Osmani Nagar"
    }
    for filename in os.listdir(dir_path + '/data/'):
        print filename
        json_obj = None
        if (filename.endswith(".json")):
            with open(dir_path + '/data/' + filename, 'rb') as jsonfile:
                json_obj = json.load(jsonfile)

        for elem in json_obj:
            new_json = {}
            v_day = None
            v_month = None
            v_year = None
            new_json['violence_actor'] = []
            new_json['violence_type'] = []
            new_json['responders'] = []
            new_json['property_destroyed_type'] = []
            new_json['injuries_count'] = 0
            new_json['deaths_count'] = 0
            new_json['property_destroyed_count'] = 0
            for key in elem:
                if key in json_structure:
                    if key == 'VSOUR':
                        new_json[json_structure[key]] = violence_source[str(elem[key])]
                    elif key == 'NDPRO1' or key == 'NDPRO2' or key == 'NDPRO3':
                        if elem[key] == '' or elem[key] == 'Imprecise' or elem[key] == 'imprecise' or elem[key] == None:
                            pass
                        else:
                            new_json['property_destroyed_count'] += int(elem[key])
                    elif key == 'CAviolence_type_1SACA' or key == 'CASACB':
                        if elem[key] == '' or elem[key] == 'Imprecise' or elem[key] == 'imprecise' or elem[key] == None:
                            new_json[json_structure[key]] = 0

                        else:
                            new_json[json_structure[key]] = float(elem[key])
                    elif key == 'VTYP1':
                        if elem[key] == "311" or elem[key] == 311 :
                            new_json[json_structure[key]] = violence_type_1["310"]
                        elif elem[key] == 207 or elem[key] == None or elem[key] == 602 or elem[key] == 702 or elem[key] == 704 or elem[key] == 810 or elem[key] == 121:
                            #TODO: Figure out what 207, 602, 702, 704, 810, 121 means
                            new_json[json_structure[key]] = None
                        else:
                            new_json['violence_type'].append(violence_type_1[str(elem[key])])
                    elif key == 'VTYP2':
                        if elem[key] == "311"  or elem[key] == 311:
                            new_json['violence_type'].append(violence_type_1["310"])
                        elif elem[key] == '321' or elem[key] == '140' or elem[key] == '' or elem[key]== None or elem[key] == 301:
                            pass
                        else:
                            new_json['violence_type'].append(violence_type_1[str(elem[key])])
                    elif key == 'VTYP3':
                        if elem[key] == '' or elem[key] == None:
                            pass
                        else:
                            new_json['violence_type'].append(violence_type_1[str(elem[key])])
                    elif key == "VTRIG1" or key == "VTRIG2":
                        if elem[key] == '240':
                            new_json[json_structure[key]] = violence_trigger_1[re.sub("\D", "", str("230"))]
                        elif elem[key] == "111" or elem[key] == 111:
                            new_json[json_structure[key]] = violence_trigger_1[re.sub("\D", "", str("110"))]
                        elif elem[key] == "199":
                            new_json[json_structure[key]] = violence_trigger_1[re.sub("\D", "", str("190"))]
                        elif elem[key] == None or elem[key] == "" or elem[key] == 995:
                            #TODO: Figure out what 995 means
                            new_json[json_structure[key]] = None
                        else:
                            new_json[json_structure[key]] = violence_trigger_1[re.sub("\D", "", str(elem[key]))]
                    elif key == "LDIS":
                        if re.sub("\D", "", str(elem[key])) == "417":
                            new_json[json_structure[key]] = event_location_district["317"]
                        elif re.sub("\D", "", str(elem[key])) == '30':
                            new_json[json_structure[key]] = event_location_district["301"]
                        else:
                            new_json[json_structure[key]] = event_location_district[re.sub("\D", "", str(elem[key]))]
                    elif key == "VTRIGC":
                        if re.sub("\D", "", str(elem[key])) == "1":
                            new_json[json_structure[key]] = "Yes"
                        else:
                            new_json[json_structure[key]] = "No"
                    elif key == "VACTA1" or key == "VACTA2" or key == "VACTA3" or key == "VACTB1" or key == "VACTB2" or key == "VACTB3":
                        if elem[key] == None or elem[key] == '' or elem[key] == '32' or elem[key] == '299' or elem[key] == 790 :
                            #TODO: Figure out what 32, 299, 790 means
                            pass
                        else:
                            new_json['violence_actor'].append(violence_actor_1[re.sub("\D", "", str(elem[key]))])
                    elif key == "VNUM":
                        new_json[json_structure[key]] = int(elem[key])
                    elif key == "VPOL":
                        if elem[key] == None or elem[key] == 1000:
                            new_json[json_structure[key]] = None
                        else:
                            new_json[json_structure[key]] = violence_police_role[str(elem[key])]
                    elif key == "DPROP1":
                        if elem[key] == None or elem[key] == 770 or elem[key] == 8500:
                            pass
                        else:
                            new_json[json_structure[key]] = destruction_of_property[str(elem[key])]
                            new_json['property_destroyed_type'].append(destruction_of_property[str(elem[key])])
                    elif key == "DPROP2":
                        if elem[key] == None or elem[key] == 1:
                            pass
                        elif elem[key] == '8401':
                            new_json['property_destroyed_type'].append(destruction_of_property['840'])
                        else:
                            new_json['property_destroyed_type'].append(destruction_of_property[str(elem[key])])
                    elif key == "DPROP3":
                        if elem[key] == None or elem[key] == 3:
                            pass
                        elif elem[key] == '8401' or elem[key] == '1':
                            new_json[json_structure[key]] = destruction_of_property['100']
                            new_json['property_destroyed_type'].append(destruction_of_property['100'])
                        else:
                            new_json[json_structure[key]] = destruction_of_property[str(elem[key])]
                            new_json['property_destroyed_type'].append(destruction_of_property[str(elem[key])])
                    elif key == "VTAR1" or key == "VTAR2" or key == "VTAR3":
                        if elem[key] == '' or elem[key] == None or elem[key] == '188:supporters of union parishad chairman':
                            new_json[json_structure[key]] = None
                        elif elem[key] == '210*' :
                            new_json['responders'].append(violence_actor_1['210'])
                        else:
                            new_json['responders'].append(violence_actor_1[str(elem[key])])
                    elif key == 'WOUACA':
                        if elem[key] == '' or elem[key]==None:
                            new_json['injuries_count'] += float(0)
                        elif elem[key] == 'imprecise':
                            new_json['injuries_count'] += float(0)
                        else:
                            new_json['injuries_count'] += float(elem[key])
                    elif key == 'WOUACB':
                        if elem[key] == '' or elem[key] == None:
                            new_json['injuries_count'] += float(0)
                        elif elem[key] == 'imprecise':
                            new_json['injuries_count'] += float(0)
                        else:
                            new_json['injuries_count'] += float(elem[key])

                    elif key == 'CASACA' or key == 'CASACB':
                        if elem[key] == '' or elem[key] == None:
                            new_json['deaths_count'] += float(0)
                        elif elem[key] == 'imprecise':
                            new_json['deaths_count'] += float(0)
                        else:
                            new_json['deaths_count'] += float(elem[key])
                    elif key == 'CASTAR':
                        if elem[key] == '' or elem[key] == ' ' or elem[key] == '`' or elem[key] == None:
                            new_json['deaths_count'] += float(0)
                        elif elem[key] == 'imprecise':
                            new_json['deaths_count'] += float(0)
                        else:
                            new_json['deaths_count'] += float(elem[key])
                    elif key == 'VNUM':
                        if elem[key] == '':
                            new_json[json_structure[key]] = 0
                        else:
                            new_json[json_structure[key]] = int(elem[key])
                    elif key == 'LUPC':
                        if elem[key] == '':
                            new_json[json_structure[key]] = ""
                        elif elem[key] == '800001' or elem[key] == '30100':
                            new_json[json_structure[key]] = "multiple"
                        elif elem[key] == '508012' or elem[key] =='508010' or elem[key] =='508011':
                            new_json[json_structure[key]] = upazila['508002']
                        else:
                            new_json[json_structure[key]] = upazila[str(elem[key])]
                    elif key =='VDAY':
                        if key == None:
                            v_day = 1
                            new_json[json_structure[key]] = elem[key]
                        else:
                            v_day = elem['VDAY']
                            new_json[json_structure[key]] = elem[key]
                    elif key == 'VMONT':
                        if key == None or key == '':
                            v_month = 1
                            new_json[json_structure[key]] = elem[key]
                        else:
                            v_month = elem['VMONT']
                            new_json[json_structure[key]] = elem[key]
                    elif key =='VYEAR':
                        print elem['VYEAR']
                        if elem['VYEAR'] == '2103':
                            print "DID IT"
                            new_json[json_structure[key]] = 2013
                            v_year = 2013
                        else:
                            v_year = elem['VYEAR']
                            new_json[json_structure[key]] = elem[key]
                            # print v_year
                    else:
                        new_json[json_structure[key]] = elem[key]

                    if key == "LDIS":
                        division_number = elem["LDIS"]

                        if elem["LDIS"] == '30`':
                            division_number = 300
                        else:
                            division_number = int(division_number)
                        if division_number >= 100 and division_number < 200:
                            new_json['division'] = 'Barisal'
                        elif division_number >= 200 and division_number < 300:
                            new_json['division'] = 'Chittagong'
                        elif division_number >= 300 and division_number < 400:
                            new_json['division'] = 'Dhaka'
                        elif division_number >= 400 and division_number < 500:
                            new_json['division'] = 'Khulna'
                        elif division_number >= 500 and division_number < 600:
                            new_json['division'] = 'Rajshahi'
                        elif division_number >= 600 and division_number  < 700:
                            new_json['division'] = 'Rangpur'
                        elif division_number >= 700 and division_number < 800:
                            new_json['division'] = 'Sylhet'
                        elif division_number == 800:
                            new_json['division'] = 'Multiple'
            if v_day and v_month and v_year:
                # print str(v_day) + ' - ' + str(v_month)
                try:
                    datetime_object = datetime.strptime(str(v_day)+' '+str(v_month)+' '+str(v_year), '%d %m %Y')
                    new_json['incident_date'] = datetime_object
                except:
                    pass
            new_json['state'] = 'Bangladesh'
            collection.insert(new_json)

    print "Importing finished"


parse()
